name: flutter_clean_core
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  dio: ^5.1.1
  retrofit: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  jwt_decoder: ^2.0.1

  dartz: ^0.10.1
  injectable: ^2.1.1
  get_it: ^7.5.0
  freezed_annotation: ^2.2.0

  firebase_core: any
  firebase_auth: any
  google_sign_in: any
  firebase_messaging: any
  flutter_local_notifications: any

  permission_handler: ^10.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  go_router: ^3.1.1

  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.3
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  retrofit_generator: ^6.0.0+3
  json_serializable: ^6.6.2
  hive_generator: ^2.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter_Black.ttf
          weight: 900
        - asset: assets/font/Inter_Bold.ttf
          weight: 700
        - asset: assets/font/Inter_Regular.ttf
          weight: 600
        - asset: assets/font/Inter_Medium.ttf
          weight: 500
        - asset: assets/font/Inter_Light.ttf
          weight: 300
        - asset: assets/font/Inter_ExtraLight.ttf
          weight: 200
        - asset: assets/font/Inter_Thin.ttf
          weight: 100